### ISSUE TITLE
Time sync needed for services<->1.0 builder/nomad

### ISSUE THREAD

**Issue by jjethwa** [circleci/enterprise-setup#142]
PR submitted: https://github.com/circleci/enterprise-setup/pull/141

**Comment by jjethwa** [comment]
Updated PR to include setting clocksource to tsc: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-linux-performance/

**Comment by MikeyYeahYeah** [comment]
Thanks for creating this issue!  We addressed this in https://github.com/circleci/enterprise-setup/pull/144 . Let me know if this works for you.

**Comment by jjethwa** [comment]
Hi @MikeyYeahYeah 

NTP works, but timesyncd might be preferred as it implements client code only, so it's considered more lightweight and secure.

You might want to add the clocksource config for performance reasons as well.  Thanks 👍
