### ISSUE TITLE
Request:  Allow a warning status on build

### ISSUE THREAD

**Issue by CarrieEBeaton** [circleci/enterprise-setup#195]
Hi, my team is integrating performance metrics into the build and we would like the ability to have a job with a status of warning that turns yellow instead of just having the success/fail statuses.  Is that something that can be done?  I would be happy to contribute to make that happen. 

Thanks!

Carrie

**Comment by nsmith5** [comment]
Hi Carrie!

Its not possible now, but certainly something you can request as a feature here https://circleci.canny.io/.  Unfortunately that part of our code base isn't opensource so we can't accept contributions, but thanks so much for the offer. 

You might also find some folks that have solutions to your use case if you ask in our forum here: https://discuss.circleci.com/

Cheers
